@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOiIxZmEyZTAyMC02OWE2LTRjOWItODBlZS04MDllMjE3NmUzM2IiLCJ1c2VybmFtZSI6ImFfaGFueSIsImZpcnN0bmFtZSI6ImFobWVkIiwibGFzdG5hbWUiOiJoYW55IiwiaGFzaCI6IiQyYiQxMCRLOHdVSmlXdnJTRDRuZEZSVllHazd1WGovOFBUbEFTN2RpWnV2TXBYZDlRRks2Q05yVks5TyIsInVzZXJfY3JlYXRlZF9hdCI6IjIwMjMtMDItMTJUMTU6NDM6MjkuODk4WiJ9LCJpYXQiOjE2NzYyMjQwNDh9.8Gqy3JzMPx1q_1BUf9v2aAP7Zr9gNN_TJ1AGdN-d9Xo
@userID = 1fa2e020-69a6-4c9b-80ee-809e2176e33b
@productID1 = 3381d7b7-7b32-4765-b256-964f0ea920af
@productID2 = cec3df70-4c57-4bb5-a001-41692e48833a
@productID3 = bf6996ac-c032-4d62-a54b-5272bdce7794
####################################################################
# User SignUp
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "a_hany",
    "firstName": "ahmed",
    "lastName": "hany",
    "password": "ahmed_password"
}

####################################################################
# Get All Users
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Get User By ID
GET http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Update User
PUT http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

{
      "username": "a_hany",
      "firstName": "ahmed",
      "lastName": "hany",
      "password": "ahmed_password"
}

####################################################################
# Delete User
DELETE http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

####################################################################
# User Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "a_hany",
    "password": "ahmed_password"
}

####################################################################
# User Logout
GET http://localhost:3000/api/auth/logout
Content-Type: application/json

####################################################################
#  Get Products
GET http://localhost:3000/api/products
Content-Type: application/json

####################################################################  
# Create Product
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: {{token}}

{
  "name": "product",
  "price": 9.99
}

####################################################################
# Get Product by ID
GET http://localhost:3000/api/products/{{productID2}}
Content-Type: application/json

####################################################################
# Create a User's order
POST http://localhost:3000/api/users/{{userID}}/orders
Content-Type: application/json
Authorization: {{token}}

{
  "items": [
    {
      "product_id": "{{productID1}}",
      "quantity": 3
    },
    {
      "product_id": "{{productID2}}",
      "quantity": 2
    },
    {
      "product_id": "{{productID3}}",
      "quantity": 14
    }
  ],
  "status": "active"
}

####################################################################
# Get a User's order
GET http://localhost:3000/api/users/{{userID}}/orders
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Get a User's active order
GET http://localhost:3000/api/users/{{userID}}/orders/active
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Get a User's completed order
GET http://localhost:3000/api/users/{{userID}}/orders/completed
Content-Type: application/json
Authorization: {{token}}

####################################################################
