@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOiI1YmU0MjQ0ZC1kN2VkLTQxYjItYjI4OS01MjU3ZTYzOWI1YTQiLCJ1c2VybmFtZSI6ImFfaGFueSIsImZpcnN0bmFtZSI6ImFobWVkIiwibGFzdG5hbWUiOiJoYW55IiwiaGFzaCI6IiQyYiQxMCRBTlRrUEpqM1hwVXZSUHgySGlwM2ZPQ0E3MDZ4Q3hqcXBMS1BuLm12VVRjOU16MVc3cVhLdSIsInVzZXJfY3JlYXRlZF9hdCI6IjIwMjMtMDItMTFUMTQ6NTQ6MjUuODcwWiJ9LCJpYXQiOjE2NzYxMzQ0Njl9.9YEybiVeLKEIZMwjPp1wMeQtWzdBfQ7Xzsju3HWX6zg
@userID = 5be4244d-d7ed-41b2-b289-5257e639b5a4
@productID1 = 951687db-b543-4bcd-89a4-a287e1ff62f8
@productID2 = 6c38ce28-f3a3-4e75-9d74-4ae4839097e9
@productID3 = 1dea26a7-219f-4426-be89-2b2347f4d573
####################################################################
# User SignUp
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "a_hany",
    "firstName": "ahmed",
    "lastName": "hany",
    "password": "ahmed_password"
}

####################################################################
# Get All Users
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Get User By ID
GET http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Update User
PUT http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

{
      "username": "a_hany",
      "firstName": "ahmed",
      "lastName": "hany",
      "password": "ahmed_password"
}

####################################################################
# Delete User
DELETE http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

####################################################################
# User Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "a_hany",
    "password": "ahmed_password"
}

####################################################################
# User Logout
GET http://localhost:3000/api/auth/logout
Content-Type: application/json

####################################################################
#  Get Products
GET http://localhost:3000/api/products
Content-Type: application/json

####################################################################  
# Create Product
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: {{token}}

{
  "name": "product",
  "price": 9.99
}

####################################################################
# Get Product by ID
GET http://localhost:3000/api/products/{{productID2}}
Content-Type: application/json

####################################################################
# Create a User's order
POST http://localhost:3000/api/users/{{userID}}/orders
Content-Type: application/json
Authorization: {{token}}

{
  "items": [
    {
      "product_id": "{{productID1}}",
      "quantity": 3
    },
    {
      "product_id": "{{productID2}}",
      "quantity": 2
    },
    {
      "product_id": "{{productID2}}",
      "quantity": 14
    }
  ],
  "status": "active"
}

####################################################################
# Get a User's order
GET http://localhost:3000/api/users/{{userID}}/orders
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Get a User's active order
GET http://localhost:3000/api/users/{{userID}}/orders/active
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Get a User's completed order
GET http://localhost:3000/api/users/{{userID}}/orders/completed
Content-Type: application/json
Authorization: {{token}}

####################################################################
