@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMWViZGQwNjctMTU1Ny00ZTYwLThmNWQtZTc4ZmIzMTlkNTQzIiwidXNlcm5hbWUiOiJhX2hhbnkiLCJmaXJzdG5hbWUiOiJhaG1lZCIsImxhc3RuYW1lIjoiaGFueSIsImhhc2giOiIkMmIkMTAkUTAzRFF0aWNTWEgvNTZvb05DYS9LdWouSlo3eldGU0ptaGNhQk10ekpnZFBpSjludlBkOXEifSwiaWF0IjoxNjc0NDIwMzY1fQ.39XpmDdExlpmBmUWXhKSwC11iFR8Ehh4U3nwuGS1gHA
@userID = 1ebdd067-1557-4e60-8f5d-e78fb319d543
@productID = 16a2a050-5b7a-433b-b4d3-fe599e70ed08
####################################################################
# User SignUp
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "a_hany",
    "firstName": "ahmed",
    "lastName": "hany",
    "password": "ahmed_password"
}

####################################################################
# Get All Users
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Get User By ID
GET http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

####################################################################
# Update User
PUT http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

{
      "username": "a_hany",
      "firstName": "ahmed",
      "lastName": "hany",
      "password": "ahmed_password"
}

####################################################################
# Delete User
DELETE http://localhost:3000/api/users/{{userID}}
Content-Type: application/json
Authorization: {{token}}

####################################################################
# User Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "a_hany",
    "password": "ahmed_password"
}

####################################################################
# User Signout
GET http://localhost:3000/api/auth/logout
Content-Type: application/json

####################################################################
#  Get Products
GET http://localhost:3000/api/products
Content-Type: application/json

####################################################################  
# Create Product
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: {{token}}

{
  "name": "product1",
  "price": 9.99
}

####################################################################
# Create Product by ID
GET http://localhost:3000/api/products/{{productID}}
Content-Type: application/json

####################################################################
# Create a User's order
POST http://localhost:3000/api/users/{{userID}}/orders
Content-Type: application/json
Authorization: {{token}}

{
  "product_id": "987f24fa-467d-403e-8fc9-8c50d700c13a",
  "status": "active"
}

####################################################################
# Get a User's order
GET http://localhost:3000/api/users/{{userID}}/orders
Content-Type: application/json
Authorization: {{token}}

####################################################################
