version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_USER:$${DB_USER}
      - POSTGRES_PASSWORD:$${DB_PASSWORD}
      - POSTGRES_DB:$${POSTGRES_DB_NAME}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres: