version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres: